#ifndef DANMAKUCONSTANTS_H
#define DANMAKUCONSTANTS_H

#define DANMAKU_FPS 60
#define DANMAKU_STANDARD_RAIL_CNT 18
#define DANMAKU_DEFAULT_TEXT_WEIGHT 1000
#define DANMAKU_RECONNECT_INTERVAL 4000
#define DANMAKU_SHUTDOWN_INTERVAL 2500
#define DANMAKU_PERMISSION_ALLOW 1

#endif // DANMAKUCONSTANTS_H
