#ifndef DANMAKUCONSTANTS_H
#define DANMAKUCONSTANTS_H

#define DANMAKU_FPS 60
#define DANMAKU_STANDARD_RAIL_CNT 18
#define DANMAKU_DEFAULT_FONT "SimHei"
#define DANMAKU_DEFAULT_TEXT_WEIGHT 1000

#endif // DANMAKUCONSTANTS_H
