#ifndef NETWORKCONFIG_H
#define NETWORKCONFIG_H

#include <QString>

#define DANMAKU_WS_PING_INTERVAL 500
#define DANMAKU_INITIAL_RECONNECT_COUNTDOWN 2
#define DANMAKU_MAX_RECONNECT_COUNTDOWN 50

//#define DANMAKU_DEBUG

// #define DANMAKU_DOMAIN QString("danmakuit.panda2134.site")
#define DANMAKU_SCHEMA QString("wss")

#endif // NETWORKCONFIG_H
