name: CI Test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    msvc2019:
    name: Windows MSVC2019
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Qt
        shell: pwsh
        run: |
          pip install aqtinstall==2.0.5
          aqt install-qt windows desktop 6.2.2 win64_msvc2019_64 -m qtwebsockets -O ./Qt
          Convert-Path ./Qt/6.2.2/msvc2019_64/bin | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          
      - name: Build
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          qmake
          nmake

      - name: Package
        shell: pwsh
          run: |
            $targetName = DanmaKuItDesktop.exe
            $archiveName = DanmaKuItDesktop_MSVC2019
            New-Item -ItemType Directory $archiveName
            Copy-Item bin/release/$targetName $archiveName/
            windeployqt --qmldir . --plugindir $archiveName/plugins --no-translations --compiler-runtime $archiveName/$targetName
            $removeList = @('*.qmlc', '*.ilk', '*.exp', '*.lib', '*.pdb')
            Get-ChildItem -Path $archiveName -Include $removeList -Recurse | Remove-Item
            $redistDll='{0}{1}\*.CRT\*.dll' -f $env:vcToolsRedistDir.Trim(), $env:msvcArch
            Copy-Item $redistDll $archiveName/
            $sdkDll='{0}Redist\{1}ucrt\DLLs\{2}\*.dll' -f $env:winSdkDir.Trim(), $env:winSdkVer.Trim(), $env:msvcArch
            Copy-Item $sdkDll $archiveName/
            Compress-Archive -Path $archiveName $archiveName'.zip'
            echo '::set-output name=packageName::$archiveName'

      - name: Upload to release
        if: startsWith(github.event.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.package.outputs.packageName }}.zip
          asset_name: ${{ steps.package.outputs.packageName }}.zip
          tag: ${{ github.ref }}
          overwrite: true